name: Restful Booker API Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        BOOKING_USER: ${{ secrets.BOOKING_USER }}
        BOOKING_PASSWORD: ${{ secrets.BOOKING_PASSWORD }}

    - name: Upload Allure Results Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30